// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI8n_quv285WbQKUmpWvwnDbnXbxae8_o',
    appId: '1:481544287499:web:f4171c65365c7ea4269e0e',
    messagingSenderId: '481544287499',
    projectId: 'flutterproject-4a86c',
    authDomain: 'flutterproject-4a86c.firebaseapp.com',
    storageBucket: 'flutterproject-4a86c.firebasestorage.app',
    measurementId: 'G-NNS24C4DTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPtVjkKb1NNOqyC5t8GJ2FvpFTyfj7DpE',
    appId: '1:481544287499:android:6f176f53151bf6f2269e0e',
    messagingSenderId: '481544287499',
    projectId: 'flutterproject-4a86c',
    storageBucket: 'flutterproject-4a86c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2YZmt1nYkmcyVwjn6tKYRyOCJKJGWJ0',
    appId: '1:481544287499:ios:b86df79f62c28624269e0e',
    messagingSenderId: '481544287499',
    projectId: 'flutterproject-4a86c',
    storageBucket: 'flutterproject-4a86c.firebasestorage.app',
    iosBundleId: 'com.example.lmsMobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS2YZmt1nYkmcyVwjn6tKYRyOCJKJGWJ0',
    appId: '1:481544287499:ios:b86df79f62c28624269e0e',
    messagingSenderId: '481544287499',
    projectId: 'flutterproject-4a86c',
    storageBucket: 'flutterproject-4a86c.firebasestorage.app',
    iosBundleId: 'com.example.lmsMobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI8n_quv285WbQKUmpWvwnDbnXbxae8_o',
    appId: '1:481544287499:web:1cadd62ce5310af9269e0e',
    messagingSenderId: '481544287499',
    projectId: 'flutterproject-4a86c',
    authDomain: 'flutterproject-4a86c.firebaseapp.com',
    storageBucket: 'flutterproject-4a86c.firebasestorage.app',
    measurementId: 'G-Y5FJYNP0ML',
  );
}
